### ISSUE TITLE
Thanks for great library

### ISSUE THREAD

**Issue by kapilpipaliya** [rolinger/country-data#1]
Thanks for great library
India has no currency symbol:
https://github.com/rolinger/iso-country-data-validation/blob/master/CountryData_pretty.json#L6501

**Comment by rolinger** [comment]
@kapilpipaliya - are you saying India doesn't have a currency symbol and my data is wrong...OR are you saying my data is missing the currency symbol for India?  If it's missing from my data, please provide me the currency symbol and I will get it added.

**Comment by kapilpipaliya** [comment]
Thanks. https://en.wikipedia.org/wiki/Indian_rupee_sign 
₹

**Comment by rolinger** [comment]
@kapilpipaliya - India and Haitian currency codes were updated.

**Comment by kapilpipaliya** [comment]
oh Thanks.
